name: Github secrets test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   
    
    steps:
      - name: Print GitHub Secret
        run: echo "My secret value is ${{ secrets.MY_SECRET }}"
