name: Github secrets test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}  # Set the secret as an environment variable

    steps:
      - name: Print GitHub Secret
        run: echo "My secret value is $MY_SECRET"
